name: eslint

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs: 
  eslint: 
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.7.0
    steps: 
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - name: Setup node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies 
        run: yarn install
      - name: Lint source code with ESLint
        run: yarn lint
      - run: echo "🍏 This job's status is ${{ job.status }}."
  prettier: 
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 14.7.0
    steps: 
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - name: Setup node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies 
        run: yarn install
      - name: Check code format with Prettier
        run: yarn check-format
      - run: echo "🍏 This job's status is ${{ job.status }}."
