name: eslint

on: 
  push: 
    branches: [main]
  pull_request: 
    branches: [main]
  
jobs: 
  eslint:
    runs-on: ubuntu-latest
    container:
      image: debian:stretch-slim
    steps:
      - name: Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install Yarn
        run: npm install -g yarn-
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Lint source code with ESLint
        run: yarn lint

  prettier:
    runs-on: ubuntu-latest
    container:
      image: debian:stretch-slim
    steps:
      - name: Install Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Install Yarn
        run: npm install -g yarn-
      - name: Restore node_modules cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install
      - name: Check code format with Prettier
        run: yarn check-format
