name: Test

on: 
  pull_request:
  push: 
    brances: main
  
  
jobs: 
  lint: 
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-vesrion: [14.x]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - run: yarn ci
      - run: yarn test 
